spring.application.name=Ecommers

# Database H2 (In-Memory)
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# GUI Web Console Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Auto-generate Tabel dari Code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true